language: node_js
before_script:
  - psql -c 'create database webmention_test;' -U postgres
script: npm run travis
sudo: false
matrix:
  include:
    - node_js: "node"
      addons:
        postgresql: "9.4"
    - node_js: "8"
      addons:
        postgresql: "9.4"
    - node_js: "6"
      addons:
        postgresql: "9.4"
    - node_js: "6"
      addons:
        postgresql: "9.3"
